frr defaults traditional
hostname H3
!
interface lo
 ipv6 address fc00::3/128
 ipv6 router isis SRv6LAB
 isis passive
!
router isis SRv6LAB
 net 49.0001.0000.0000.0003.00
 is-type level-1
 topology ipv6-unicast
 segment-routing srv6
  locator MAIN
 !
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fcbb:bb00:3::/48
   !
  !
 !
!
